---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: nginx-ingress-external
  annotations:
    meta.helm.sh/release-name: nginx-ingress-external
    meta.helm.sh/release-namespace: nginx-ingress-external
  labels:
    app.kubernetes.io/name: nginx-ingress-external-ingress-nginx-controller
    app.kubernetes.io/part-of: nginx-ingress-external-ingress-nginx-controller
    app.kubernetes.io/managed-by: Helm
data:
  22: "gitlab/gitlab-prod-gitlab-shell:22"
