---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  path: "cluster/cert-manager/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
