---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: clusterissuer
  namespace: cert-manager
spec:
  interval: 1m
  path: "cluster/cert-manager/issuers"
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
