---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: discord-url
  namespace: flux-system
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/infra-prod-cluster/items/discord-webhook-flux"
