---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus
    app.kubernetes.io/instance: prometheus
    release: prometheus
  name: prometheus-login-rules
  namespace: prometheus
spec:
  groups:
    - name: pod-behaviour
      rules:
        - alert: KubernetesPodNotHealthy
          expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Kubernetes Pod not healthy (instance {{ $labels.instance }})
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is in a non-running state.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - name: psql
      rules:
        - alert: psql-storage-usage-high
          expr: (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~".*psql.*"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~".*psql.*"})*100 > 85
          for: 3m
          labels:
            severity: critical
          annotations:
            summary: PSQL storage usage high (PVC {{ $labels.persistentvolumeclaim }})
            description: "Persistent volume claim {{ $labels.persistentvolumeclaim }} is more than 85% full.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"