---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus
    app.kubernetes.io/instance: prometheus
    release: prometheus
  name: prometheus-login-rules
  namespace: prometheus
spec:
  groups:
    - name: pod-behaviour
      rules:
        - alert: KubernetesPodNotHealthy
          expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
          for: 1m
          labels:
            severity: critical
            ruleset: login-custom
          annotations:
            summary: Kubernetes Pod not healthy (instance {{ $labels.instance }})
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is in a non-running state.\n  VALUE = {{ $value }}"
    - name: volumes-and-storage
      rules:
        - alert: storage-usage-high-50
          expr: |-
            (1-(kubelet_volume_stats_available_bytes / 
            kubelet_volume_stats_capacity_bytes))*100 > 50 and 
            (1-(kubelet_volume_stats_available_bytes / 
            kubelet_volume_stats_capacity_bytes))*100 <= 85
          for: 3m
          labels:
            severity: warning
            ruleset: login-custom
          annotations:
            summary: Storage usage is above 50% (PVC {{ $labels.persistentvolumeclaim }})
            description: "Persistent volume claim {{ $labels.persistentvolumeclaim }} is more than 50% full.\n  VALUE = {{ $value }}"
        - alert: storage-usage-high-85
          expr: |-
            (1-(kubelet_volume_stats_available_bytes / 
            kubelet_volume_stats_capacity_bytes))*100 > 85 and 
            (1-(kubelet_volume_stats_available_bytes / 
            kubelet_volume_stats_capacity_bytes))*100 <= 95
          for: 3m
          labels:
            severity: warning
            ruleset: login-custom
          annotations:
            summary: Storage usage is above 85% (PVC {{ $labels.persistentvolumeclaim }})
            description: "Persistent volume claim {{ $labels.persistentvolumeclaim }} is more than 85% full.\n  VALUE = {{ $value }}"
        - alert: storage-usage-high-95
          expr: |-
            (1-(kubelet_volume_stats_available_bytes / 
            kubelet_volume_stats_capacity_bytes))*100 > 95
          for: 3m
          labels:
            severity: critical
            ruleset: login-custom
          annotations:
            summary: Storage usage is above 95% (PVC {{ $labels.persistentvolumeclaim }})
            description: "Persistent volume claim {{ $labels.persistentvolumeclaim }} is more than 95% full.\n  VALUE = {{ $value }}"
    - name: psql
      rules:
        - alert: psql-wal-age-one-hour
          expr: |-
            max by(pod) ((1 - cnpg_pg_replication_in_recovery) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival) + 
            cnpg_pg_stat_archiver_seconds_since_last_archival)) > 3600 and max by(pod) ((1 - cnpg_pg_replication_in_recovery) * (time() - 
            timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival) + cnpg_pg_stat_archiver_seconds_since_last_archival)) <= 7200
          for: 3m
          labels:
            ruleset: login-custom
            severity: warning
          annotations:
            summary: PSQL WAL is more than 1 hour old (instance {{ $labels.pod }})
            description: "WAL for {{ $labels.pod }} is more than 1 hour old.\n  VALUE = {{ $value }}"
        - alert: psql-wal-age-two-hours
          expr: |-
            max by(pod) ((1 - cnpg_pg_replication_in_recovery) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival) + 
            cnpg_pg_stat_archiver_seconds_since_last_archival)) > 7200
          for: 3m
          labels:
            severity: critical
            ruleset: login-custom
          annotations:
            summary: PSQL WAL is more than 2 hours old (instance {{ $labels.pod }})
            description: "WAL for {{ $labels.pod }} is more than 2 hours old.\n  VALUE = {{ $value }}"