---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "62.3.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
        namespace: prometheus
      interval: 5m
  values:
    grafana:
      enabled: false
    crds:
      enabled: true
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx-ntnu
        hosts:
          - prometheus-infra.login.no
        paths:
          - /
        tls:
          - secretName: prometheus-infra-tls
            hosts:
              - prometheus-infra.login.no
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: do-block-storage
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 8Gi
          selector: {}
