---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: "25.26.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
        namespace: prometheus
      interval: 5m
  values:
    server:
      extraArgs:
        web.route-prefix: "/"
      hostNetwork: false
      baseURL: prometheus-infra.login.no
      persistentVolume:
        storageClass: do-block-storage
      service:
        enabled: true
        type: NodePort
        nodePort: 32050
        annotations:
          kubernetes.digitalocean.com/firewall-managed: "false"