---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "65.6.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
        namespace: prometheus
      interval: 5m
  values:
    grafana:
      enabled: false
    crds:
      enabled: true
    prometheus:
      service:
        type: NodePort
        nodePort: 32050
      ingress:
        enabled: true
        ingressClassName: nginx-ntnu
        hosts:
          - prometheus-infra.login.no
        paths:
          - /
        tls:
          - secretName: prometheus-infra-tls
            hosts:
              - prometheus-infra.login.no
      prometheusSpec:
        loglevel: debug
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        podMonitorSelector: {}
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: do-block-storage-retain
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
        externalUrl: https://prometheus-infra.login.no
    alertmanager:
      enabled: true
      ingress: 
        enabled: true
        ingressClassName: nginx-ntnu
        hosts:
          - alertmanager-infra.login.no
        paths:
          - /
        tls:
          - secretName: alertmanager-infra-tls
            hosts:
              - alertmanager-infra.login.no
      config:
        route:
          receiver: 'email'
          group_by: ['alertname']
          group_wait: 5s
          group_interval: 1m
          repeat_interval: 5h
        receivers:
          - name: 'email'
            email_configs:
              - send_resolved: true
                to: 'support@login.no'
                from: 'notifikasjon@login.no'
                smarthost: 'secure.emailsrvr.com:465'
                auth_username: 'notifikasjon@login.no'
                auth_password_file: /etc/alertmanager/secrets/prometheus-email-password/password
      alertmanagerSpec:
        loglevel: debug
        logFormat: json
        secrets:
          - prometheus-email-password
        externalUrl: https://alertmanager-infra.login.no


