---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 5m
  path: "cluster/crowdsec/crowdsec-kust"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
