---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-constraints
  namespace: beekeeper
spec:
  limits:
    - default:
        cpu: 2000m
        memory: 2048Mi
      defaultRequest:
        cpu: 1000m
        memory: 1024Mi
      max:
        cpu: 2000m
        memory: 2Gi
      min:
        cpu: 500m
        memory: 512Mi
      type: Container
