---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: test-kube-runner
  namespace: gitlab-runners
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab-runner
      version: "0.61.2"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: gitlab-runners
      interval: 1m
  values:
    replicas: 3
    imagePullPolicy: IfNotPresent
    gitlabUrl: https://git.logntnu.no/
    terminationGracePeriodSeconds: 3600
    concurrent: 10
    checkInterval: 30
    rbac:
      create: true
      rules: []
      clusterWideAccess: false
      podSecurityPolicy:
        enabled: false
        resourceNames:
          - gitlab-runner
    metrics:
      enabled: true
    runners:
      secret: test-runner-token
      config: |
        [[runners]]
          [runners.features_flag]
             ci_job_token_scope = true
          [runners.kubernetes]
            namespace = "{{.Release.Namespace}}"
            image = "ubuntu:22.04"
      executor: kubernetes
    service:
      enable: false
