apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-psql-workerbee-psql-test2
  namespace: workerbee
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      cnpg.io/cluster: workerbee-psql-test2
  ingress:
    - {}
  egress:
    - {}