---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: test-runner-token
  namespace: gitlab-runners
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/helms-deep-k8s-infra-prod/items/runer-kub-test"
