---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-ntnu-ingress-nginx-controller
  namespace: nginx-ingress-ntnu
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: nginx-ingress-ntnu
    meta.helm.sh/release-namespace: nginx-ingress-ntnu
data:
  # Setting security headers
  add-headers: "nginx-ingress-ntnu/custom-headers"
  hide-headers: "Server,X-Powered-By"

  # SSL configuration
  ssl-redirect: "true"
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-prefer-server-ciphers: "true"
  ssl-dh-param: "nginx-ingress-ntnu/lb-dhparam"
  ssl-ecdh-curve: "secp384r1"
  ssl-ciphers: "HIGH:!EXP:!NULL:!ADH:!LOW:!SSLv2:!SSLv3:!MD5:!RC4"
  enable-ocsp: "true"
  hsts: "true"
  hsts-include-subdomains: "true"
  hsts-max: "15552000"
  ssl-session-cache: "true"
  ssl-session-cache-size: "10m"

  # DO proxy settings
  use-proxy-protocol: "true"
  enable-real-ip: "true"
  proxy-real-ip-cidr: "10.0.0.0/8"

  # Timeouts
  proxy-connect-timeout: "100"
  proxy-read-timeout: "100"
  keepalive-timeout: "100s"
  proxy-send-timeout: "100"
  client-header-timeout: "100"

  # Div configs
  use_http2: "true"
  server-tokens: "false"
  proxy-body-size: "100K"
  large-client-header-buffers: "2 1k"
  proxy-headers-hash-max-size: "1024"
  proxy-headers-hash-bucket-size: "128"

  # Logging
  log-format-upstream: '{ "nginx_timestamp": "$time_iso8601", "remote_addr": "$remote_addr", "connection": "$connection", "connection_requests": $connection_requests, "pipe": "$pipe", "body_bytes_sent": $body_bytes_sent, "request_length": $request_length, "request_time": $request_time, "response_status": $status, "request": "$request", "request_method": "$request_method", "host": "$host", "upstream_cache_status": "$upstream_cache_status", "upstream_addr": "$upstream_addr", "http_x_forwarded_for": "$http_x_forwarded_for", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent", "http_version": "$server_protocol", "remote_user": "$remote_user", "http_x_forwarded_proto": "$http_x_forwarded_proto", "upstream_response_time": "$upstream_response_time", "nginx_access": true }'
  enable-access-log-for-default-backend: "true"
  log-format-escape-json: "true"
