---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 1pwdsecrets
  namespace: nginx-ingress-ntnu
spec:
  interval: 1m
  path: "cluster/nginx-ingress-ntnu/secrets"
  dependsOn:
    - name: 1password-connect
      namespace: 1pwd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
