---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-psql
  namespace: gitlab
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 8Gi
  postgresql:
    parameters:
      timezone: "Europe/Oslo"
  bootstrap:
    initdb:
      database: gitlab
      owner: gitlab
      secret:
        name: gitlab-db-credentials
