---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-psql
  namespace: gitlab
spec:
  monitoring:
    enablePodMonitor: true
  description: Postgres for GitLab
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:15.8
  storage:
    size: 10Gi
  postgresql:
    parameters:
      timezone: "Europe/Oslo"
  bootstrap:
    initdb:
      database: gitlab
      owner: gitlab
      secret:
        name: gitlab-db-credentials
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://login-infra-prod-psql-backups/gitlab
      s3Credentials:
        accessKeyId:
          name: gitlab-pg-backup
          key: access
        secretAccessKey:
          name: gitlab-pg-backup
          key: secret
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gitlab-psql
  namespace: gitlab
spec:
  podMetricsEndpoints:
    port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: gitlab-psql
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: gitlab-psql-backup
  namespace: gitlab
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  cluster:
    name: gitlab-psql
