---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-prod
  namespace: gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab
      version: "7.7.0"
      sourceRef:
        kind: HelmRepository
        name: gitlab-repo
        namespace: gitlab
      interval: 1m
  values:
    global:
      hosts:
        domain: login.no
        https: true
        gitlab:
          name: gittest.login.no
          https: true
        registry:
          name: registry.login.no
          https: true
        pages:
          name: pages.login.no
          https: true
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          nginx.ingress.kubernetes.io/upgrade-proxy: "true"
          nginx.ingress.kubernetes.io/enable-websockets: "true"
        configureCertmanager: false
        class: nginx-external
        tls:
          secretName: login-no-cert
      registry:
        bucket: gitlab-registry-storage
      minio:
        enabled: true
      gitaly:
        enabled: true
        persistence:
          storageClass: "do-block-storage-retain"
          size: 20Gi
      #       psql:
      #         host: private-db-postgresql-gitlab-test-do-user-6724543-0.c.db.ondigitalocean.com
      #           username: doadmin
      #         database: gitlab
      #         password:
      #           secret: gitlab-postgres-user
      #           key: password
      #         port: 25060
      redis:
        persistence:
          storageClass: "do-block-storage-retain"
        storageClass: "do-block-storage-retain"
      appConfig:
        lfs:
          bucket: gitlab-lfs-storage
          connection:
            secret: do-spaces-connection
            key: connection
        artifacts:
          bucket: gitlab-artifacts-storage
          connection:
            secret: do-spaces-connection
            key: connection
        uploads:
          bucket: gitlab-uploads-storage
          connection:
            secret: do-spaces-connection
            key: connection
        packages:
          bucket: gitlab-packages-storage
          connection:
            secret: do-spaces-connection
            key: connection
        backups:
          bucket: gitlab-backup-storage
          tmpBucket: gitlab-tmp-storage
        omniauth:
            enabled: true
            allow_single_sign_on: ['saml']
            sync_email_from_provider: 'saml'
            sync_profile_from_provider: ['saml']
            sync_profile_attributes: ['email']
            auto_sign_in_with_provider: 'saml'
            block_auto_created_users: false
            auto_link_saml_user: true
            providers:
              - name: 'saml'
                label: 'authentik'
                args:
                  assertion_consumer_service_url: 'https://gittest.login.no/users/auth/saml/callback'
                  idp_cert_fingerprint: 25:79:61:b4:65:2d:6c:12:1c:b2:bc:b5:1e:5b:fa:4e:e0:07:67:22
                  idp_sso_target_url: 'https://authentik.login.no/application/saml/gitlab-application/sso/binding/redirect/'
                  issuer: 'https://gittest.login.no'
                  name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'
                  attribute_statements:
                    email: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress']
                    first_name: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name']
                    nickname: ['http://schemas.goauthentik.io/2021/02/saml/username']
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    gitlab-runner:
      install: true
      runners:
        gitlabUrl: https://gitlab-prod-webservice-default:8181
    postgresql:
      install: true
    gitlab-shell:
      config:
        proxyProtocol: false
    gitlab:
      toolbox:
        backups:
          objectStorage:
            config:
              secret: do-spaces-connection
              key: connection
    registry:
      storage:
        secret: do-spaces-connection-reg
        key: connection
