---
# Added a comment.
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-prod
  namespace: gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab
      version: "7.6.0"
      sourceRef:
        kind: HelmRepository
        name: gitlab-repo
        namespace: gitlab
      interval: 1m
  values:
    global:
      hosts:
        domain: login.no
        https: true
        gitlab:
          name: gittest.login.no
          https: true
        registry:
          name: registry.login.no
          https: true
        pages:
          name: pages.login.no
          https: true
      edition: ce
      ingress:
        configureCertmanager: false
        class: nginx-external
      minio:
        enabled: true
      gitaly:
        enabled: true
        persistence:
          storageClass: "do-block-storage-retain"
          size: 50Gi
      psql:
        host: private-db-postgresql-gitlab-test-do-user-6724543-0.c.db.ondigitalocean.com
        username: doadmin
        database: gitlab
        password:
          secret: gitlab-postgres-user
          key: password
        port: 25060
      redis:
        persistence:
          storageClass: "do-block-storage-retain"
        storageClass: "do-block-storage-retain"
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    gitlab-runner:
      install: false
    postgresql:
      install: false
