---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-prod
  namespace: gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab
      version: "7.5.1"
      sourceRef:
        kind: HelmRepository
        name: gitlab-repo
        namespace: gitlab
      interval: 1m
  values:
    global:
      hosts:
        domain: test.git.login.no
      edition: ce
      ingress:
        secretName: gitlab-tls-sec
        configureCertmanager: false
        class: nginx-ntnu
    certmanager:
      install: false
