---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-prod
  namespace: gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab
      version: "8.8.1"
      sourceRef:
        kind: HelmRepository
        name: gitlab-repo
        namespace: gitlab
      interval: 5m
  values:
    global:
      hosts:
        domain: login.no
        https: true
        gitlab:
          name: gitlab.login.no
          https: true
        registry:
          name: registry.login.no
          https: true
        pages:
          name: pages.login.no
          https: true
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          nginx.ingress.kubernetes.io/upgrade-proxy: "true"
          nginx.ingress.kubernetes.io/enable-websockets: "true"
        configureCertmanager: false
        tls:
          enabled: true
          secretName: login-no-cert
        class: nginx-external
      registry:
        bucket: gitlab-login-registry-storage
      minio:
        enabled: false
      psql:
        host: gitlab-psql-rw.gitlab.svc.cluster.local
        username: gitlab
        database: gitlab
        password:
          secret: gitlab-db-credentials
          key: password
        port: 5432
      redis:
        persistence:
          storageClass: "do-block-storage-retain"
        storageClass: "do-block-storage-retain"
      serviceAccount:
        enabled: true
        create: true
      email:
        display_name: "GitLab - Login"
        from: "gitlab@login.no"
        reply_to: "kontakt@login.no"
      smtp:
        enabled: true
        address: "secure.emailsrvr.com"
        tls: true
        authentication: "plain"
        user_name: "gitlab@login.no"
        port: 465
        password:
          secret: "gitlab-email"
          key: "password"
      appConfig:
        contentSecurityPolicy:
          enabled: true
          reportOnly: false
        enableUsagePing: false
        usernameChangingEnabled: false
        sentry:
          enabled: false
        object_store:
          enabled: true
          proxy_download: true
          storage_options: {}
          connection:
            secret: gitlab-object-storage
            key: regular
        lfs:
          enabled: true
          proxy_download: true
          bucket: gitlab-login-lfs-storage
        artifacts:
          enabled: true
          proxy_download: true
          bucket: gitlab-login-artifacts
        uploads:
          enabled: true
          proxy_download: true
          bucket: gitlab-login-uploads
        packages:
          enabled: true
          proxy_download: true
          bucket: gitlab-login-packages
        externalDiffs:
          enabled: true
          when:
          proxy_download: true
          bucket: gitlab-login-mr-diffs
        terraformState:
          enabled: true
          bucket: gitlab-login-terraform-state
        dependencyProxy:
          enabled: true
          proxy_download: true
          bucket: gitlab-login-dependency-proxy
        backups:
          bucket: gitlab-login-backup-storage
          tmpBucket: gitlab-login-tmp-storage
        ciSecureFiles:
          enabled: true
          proxy_download: true
          bucket: gitlab-login-ci-secure-files
        omniauth:
          enabled: true
          autoSignInWithProvider: openid_connect
          allowSingleSignOn: ["openid_connect"]
          syncProfileFromProvider: ["openid_connect"]
          syncProfileAttributes: ["email"]
          blockAutoCreatedUsers: false
          autoLinkSamlUser: true
          autoLinkUser: ["openid_connect"]
          allowBypassTwoFactor: ["openid_connect"]
          providers:
            - secret: gitlab-oidc
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    gitlab-runner:
      install: false
    postgresql:
      install: false
    # This is IF this section is linked to subchart Prometheus
    prometheus:
      server:
        service:
          type: NodePort
          servicePort: 32051
    gitlab:
      gitlab-shell:
        config:
          proxyProtocol: false
      gitaly:
        persistence:
          enabled: true
          storageClass: "do-block-storage-retain"
          size: 20Gi
      toolbox:
        backups:
          cron:
            enabled: true
            schedule: "0 10 * * 1"
            extraArgs: --skip registry
          objectStorage:
            config:
              secret: gitlab-object-storage
              key: storage.config
    registry:
      storage:
        secret: gitlab-object-storage
        key: registry
