---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitlab-prod
  namespace: gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab
      version: "7.9.2"
      sourceRef:
        kind: HelmRepository
        name: gitlab-repo
        namespace: gitlab
      interval: 10m
  values:
    global:
      hosts:
        domain: login.no
        https: true
        gitlab:
          name: gittest.login.no
          https: true
        registry:
          name: registry.login.no
          https: true
        pages:
          name: pages.login.no
          https: true
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          nginx.ingress.kubernetes.io/upgrade-proxy: "true"
          nginx.ingress.kubernetes.io/enable-websockets: "true"
        configureCertmanager: false
        class: nginx-external
        tls:
          enabled: true
          secretName: login-no
      registry:
        bucket: gitlab-registry-storage
      minio:
        enabled: false
      gitaly:
        enabled: true
        persistence:
          storageClass: "do-block-storage-retain"
          size: 20Gi
      psql:
        host: gitlab-psql-rw.gitlab.svc.cluster.local
        username: gitlab
        database: gitlab
        password:
          secret: gitlab-db-credentials
          key: password
        port: 5432
      redis:
        persistence:
          storageClass: "do-block-storage-retain"
        storageClass: "do-block-storage-retain"
      serviceAccount:
        enabled: true
        create: true
      email:
        display_name: "GitLab - Login"
        from: "gitlab@example.com"
        reply_to: "noreply@example.com"
      smtp:
        enabled: true
        address: "smtp.example.com"
        tls: true
        authentication: "plain"
        user_name: "example"
        password:
          secret: "smtp-password"
          key: "password"
      appConfig:
        contentSecurityPolicy:
          enabled: true
          reportOnly: false
        enableUsagePing: false
        usernameChangingEnabled: false
        sentry:
          enabled: false
        object_store:
          enabled: true
          proxy_download: true
          storage_options: {}
          connection:
            secret: do-spaces-connection
            key: connection
        lfs:
          enabled: true
          proxy_download: true
          bucket: gitlab-lfs-storage
        artifacts:
          enabled: true
          proxy_download: true
          bucket: gitlab-artifacts
        uploads:
          enabled: true
          proxy_download: true
          bucket: gitlab-uploads
        packages:
          enabled: true
          proxy_download: true
          bucket: gitlab-packages
        externalDiffs:
          enabled: true
          when:
          proxy_download: true
          bucket: gitlab-mr-diffs
        terraformState:
          enabled: true
          bucket: gitlab-terraform-state
        dependencyProxy:
          enabled: true
          proxy_download: true
          bucket: gitlab-dependency-proxy
        backups:
          bucket: gitlab-backup-storage
          tmpBucket: gitlab-tmp-storage
        omniauth:
          enabled: true
          autoSignInWithProvider: saml
          allow_single_sign_on: ["saml"]
          block_auto_created_users: false
          auto_link_saml_user: true
          providers:
            - secret: gitlab-saml
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    gitlab-runner:
      install: false
    postgresql:
      install: false
    gitlab-shell:
      config:
        proxyProtocol: false
    gitlab:
      toolbox:
        backups:
          objectStorage:
            config:
              secret: storage-config
              key: config
    registry:
      storage:
        secret: do-spaces-connection-reg
        key: connection
