---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptime-kuma-smon
  namespace: uptime-kuma
  labels:
    app: uptime-kuma
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - uptime-kuma
  selector:
    matchLabels:
      app: uptime-kuma
  endpoints:
    - port: http
      path: /metrics
      basicAuth:
        password:
          name: uptime-kuma-auth
          key: password
        username:
          name: uptime-kuma-auth
          key: username
          # ptional: true

