---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: db
  namespace: wiki
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/kubernetes-ekstern-prod/items/wiki-js-DB"
