---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cloudnative-pg-repo
  namespace: psql-operator
spec:
  interval: 1m
  url: https://cloudnative-pg.github.io/charts
