---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: "v1.16.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 10m
  values:
    extraArgs:
      - --enable-certificate-owner-ref=true
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=172.64.52.210:53
    installCRDs: true
    webhook:
      timeoutSeconds: 25
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        labels:
          release: prometheus
