---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: promtail
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: "6.16.6"
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: promtail
      interval: 5m
  values:
    namespace: promtail
    daemonset:
      enabled: true
    config:
      clients:
        - url: http://loki-gateway.loki.svc.cluster.local:80/loki/api/v1/push
          tenant_id: 1
