---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: beehive
  labels:
    app: beehive-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: beehive-backend
    namespace: beehive
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
