---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network_policy.yaml
  - postgres_client.yaml
  - secret_kustomization.yaml
  # - kustomize/secrets.yaml
  # - kustomize/bot.yaml
  # - kustomize/api.yaml
  # - kustomize/db.yaml
