---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret_kustomization.yaml
  - deployment.yaml
  - network_policy.yaml
  - pdb.yaml
  - ingress.yaml
