# Denies everything except policies
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: tekkom-bot
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

# Allows Kube DNS traffic
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kube-dns
  namespace: tekkom-bot
spec:
  podSelector:
    matchLabels:
      app: tekkom-bot
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53

# Allows incoming traffic on port 6969 for mc-bot.login.no
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-api
  namespace: tekkom-bot
spec:
  podSelector:
    matchLabels:
      app: tekkom-bot
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nginx-ingress-external
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: nginx-ingress-external
      ports:
        - protocol: TCP
          port: 6969

# Allows incoming and outgoing traffic on port 8080 for the API
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress
  namespace: tekkom-bot
spec:
  podSelector:
    matchLabels:
      app: tekkom-bot-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nginx-ingress-external
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: nginx-ingress-external
      ports:
        - protocol: TCP
          port: 8080

# Allows outgoing traffic towards dizambee (zammad)
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-dizambee
  namespace: tekkom-bot
spec:
  podSelector:
    matchLabels:
      app: tekkom-bot
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: dizambee
      - podSelector:
          matchLabels:
            app: dizambee-api

# Allows api to psql traffic
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-psql
  namespace: tekkom-bot
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      cnpg.io/cluster: tekkom-bot-api-psql
  ingress:
    - {}
  egress:
    - {}

# Allows psql client traffic
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-psql-client
  namespace: tekkom-bot
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app: postgres-client
  ingress:
    - {}
  egress:
    - {}

# Allowing api to kube-dns traffic
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-to-kube-dns
  namespace: tekkom-bot
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - tekkom-bot-api
          - tekkom-bot
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53

# Allowing egress bot and bot api to internet (required for talking to Discords servers)
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-bot-egress-internet
  namespace: tekkom-bot
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - tekkom-bot
          - tekkom-bot-api
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0

# Allowing egress api to psql traffic
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-to-psql
  namespace: tekkom-bot
spec:
  podSelector:
    matchLabels:
      app: tekkom-bot-api
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: tekkom-bot-api-psql
      ports:
        - protocol: TCP
          port: 5432
