# Denies everything except policies
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: tekkom-bot
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

# Allows Kube DNS traffic
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kube-dns
  namespace: tekkom-bot
spec:
  podSelector:
    matchLabels:
      app: tekkom-bot
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53

# Allows psql client traffic
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-psql-client
  namespace: tekkom-bot
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app: postgres-client
  ingress:
    - {}
  egress:
    - {}
