apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: digitalocean-dns
  namespace: cert-manager
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/kubernetes-ekstern-prod/items/digital-ocean-dns-token"
