---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network_policy.yaml
  - secret_kustomization.yaml
  - kustomize/secrets.yaml
  - kustomize/scouterbee.yaml
