---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: beehive-ingress
  namespace: beehive-dev
spec:
  interval: 5m
  path: "cluster/beehive-dev/ingress"
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
