---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-whitelist-script
  namespace: crowdsec
data:
  whitelist.sh: |
    #!/bin/bash
    # Set the interval in seconds between IP checks (e.g., every hour)
    INTERVAL=3600

    while true; do
      # Fetch the current public IP
      PUBLIC_IP=$(curl -s https://ipconfig.io)

      if [[ -z "$PUBLIC_IP" ]]; then
        echo "$(date) - Failed to fetch public IP"
      else
        echo "$(date) - Public IP is: $PUBLIC_IP"

        # Check if the IP is already whitelisted
        EXISTING_WHITELIST=$(cscli decisions list --type whitelist --ip $PUBLIC_IP -o raw)

        if [[ -z "$EXISTING_WHITELIST" ]]; then
          # Add the whitelist decision
          cscli decisions add --ip $PUBLIC_IP --duration 0 --type whitelist --reason "Automated whitelist for the cluster IP"
          echo "$(date) - Whitelisted IP: $PUBLIC_IP"
        else
          echo "$(date) - IP $PUBLIC_IP is already whitelisted"
        fi
      fi

      # Wait for the specified interval before checking again
      sleep $INTERVAL
    done
