---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-api
  name: app-api
  namespace: app-api
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      imagePullSecrets:
        - name: gitlab-token-app-api
      containers:
        - image: registry.login.no/tekkom/apps/app-api:1.0.3
          imagePullPolicy: Always
          name: app-api
          ports:
            - containerPort: 3000
              name: 3000tcp
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - app-api
                topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: app-api
  namespace: app-api
  labels:
    app: app-api
spec:
  type: ClusterIP
  selector:
    app: app-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-api
  namespace: app-api
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
        - app.login.no
  rules:
    - host: app.login.no
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: app-api
                port:
                  number: 3000
