---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-api-pdb
  namespace: app-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: app-api

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-api-hpa
  namespace: app-api
  labels:
    app: app-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-api
    namespace: app-api
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
