---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.14.2
          args:
            - --source=ingress
            - --domain-filter=login.no
            - --provider=digitalocean
            - --txt-owner-id=inf
          env:
            - name: DO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: do-dns-token
                  key: access-token
