---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-psql
  namespace: authentik
spec:
  description: Postgres for Authentik
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  postgresql:
    parameters:
      timezone: "Europe/Oslo"
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-credentials
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://login-infra-prod-psql-backups/authentik
      s3Credentials:
        accessKeyId:
          name: authentik-pg-backup
          key: access
        secretAccessKey:
          name: authentik-pg-backup
          key: secret

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-psql-backup
  namespace: authentik
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  cluster:
    name: authentik-psql

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-restore-psql
  namespace: authentik
spec:
  description: Postgres for Authentik
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  postgresql:
    parameters:
      timezone: "Europe/Oslo"
  superuserSecret:
    name: authentik-db-credentials
  bootstrap:
    recovery:
      source: clusterBackup
      recoveryTarget:
        targetTime: "2024-09-05 08:00:00.00000+02"
  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: s3://login-infra-prod-psql-backups/authentik
        s3Credentials:
          accessKeyId:
            name: authentik-pg-backup
            key: access
          secretAccessKey:
            name: authentik-pg-backup
            key: secret
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://login-infra-prod-psql-backups/authentik-restore
      s3Credentials:
        accessKeyId:
          name: authentik-pg-backup
          key: access
        secretAccessKey:
          name: authentik-pg-backup
          key: secret
