---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-psql-test-restore
  namespace: authentik
spec:
  description: Postgres for Authentik
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 8Gi

  postgresql:
    parameters:
      timezone: "Europe/Oslo"

  bootstrap:
    recovery:
      source: authentik-psql
      database: authentik
      owner: authentik
      secret: 
        name: authentik-db-credentials

  externalClusters:
    - name: authentik-psql
      barmanObjectStore:
        destinationPath: s3://psql-backups/infra/authentik
        endpointURL: https://psql-backups.ams3.digitaloceanspaces.com
        serverName: authentik-psql
        s3Credentials:
          accessKeyId:
            name: authentik-pg-backup
            key: access
          secretAccessKey:
            name: authentik-pg-backup
            key: secret
        wal:
          maxParallel: 4

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-psql-test-restore-backup
  namespace: authentik
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  cluster:
    name: authentik-psql-test-restore
