apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-psql-v3-test
  namespace: authentik
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      cnpg.io/cluster: authentik-restore-psql-v3
  ingress:
    - {}
  egress:
    - {}