---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekkom-bot-secrets
  namespace: tekkom-bot
spec:
  interval: 5m
  path: "cluster/tekkom-bot/secrets"
  dependsOn:
    - name: 1password-connect
      namespace: 1pwd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
