---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-oidc
  namespace: grafana
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/infra-prod-cluster/items/grafana-oidc"
