---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
type: opaque
metadata:
  name: 1pwd-beekeeper-secrets-beekeeper
  namespace: beekeeper
spec:
  itemPath: "vaults/infra-prod-cluster/items/beekeeper-secrets"
