---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 10m
  chart:
    spec:
      chart: reflector
      version: "7.1.238"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: reflector
      interval: 30m
  values:
    rbac:
      enabled: true
    serviceaccount:
      create: true
