---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wiki-js
  name: wiki-js
  namespace: wiki
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wiki-js
  replicas: 3
  template:
    metadata:
      labels:
        app: wiki-js
    spec:
      containers:
        - env:
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: wiki-psql-rw.wiki.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: wiki
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wiki-db-credentials
                  key: password
            - name: DB_NAME
              value: wiki
            - name: HA_ACTIVE
              value: "1"
          image: ghcr.io/requarks/wiki:2.5.301
          imagePullPolicy: Always
          name: wiki-js
          ports:
            - containerPort: 3000
              name: 3000tcp
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          command: ["/bin/sh", "-c"]
          args: ["npm install @node-saml/passport-saml"]
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - wiki-js
              topologyKey: kubernetes.io/hostname
