---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wiki-hpa
  namespace: wiki
  labels:
    app: wiki-js
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wiki-js
    namespace: wiki
  minReplicas: 3
  maxReplicas: 9
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 1800Mi
