---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wiki-js
  namespace: wiki
spec:
  interval: 1m
  path: "cluster/wiki-js/ingress"
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

