---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: psql-operator
  namespace: psql-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.20.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-repo
        namespace: psql-operator
      interval: 1m
  values:
    replicaCount: 1
