---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: psql-operator
  namespace: psql-operator
spec:
  chart:
    spec:
      chart: cloudnative-pg
      interval: 5m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-repo
        namespace: psql-operator
      version: 0.20.0
  interval: 5m
  values:
    replicaCount: 1
