---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: psql-operator
  namespace: psql-operator
spec:
  chart:
    spec:
      chart: cloudnative-pg
      interval: 5m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-repo
        namespace: psql-operator
      version: 0.21.2
  interval: 10m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
