---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.20.0"
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: grafana
      interval: 5m
  values:
    gateway:
      service:
        type: NodePort
        nodePort: 31001
      extraContainers:
        - name: dnsmasq
          image: "janeczku/go-dnsmasq:release-1.0.7"
          imagePullPolicy: IfNotPresent
          args:
            - --listen
            - "127.0.0.1:8053"
            - --hostsfile=/etc/hosts
            - --enable-search
            - --verbose
      nginxConfig:
        resolver: "127.0.0.1:8053"
    chunksCache:
      enabled: true
      allocatedMemory: 512
    loki:
      limits_config:
        retention_period: 15w
      storage:
        type: s3
        bucketNames:
          chunks: login-loki-chunks
          ruler: login-loki-ruler
        s3:
          endpoint: "ams3.digitaloceanspaces.com"
          region: ams3
          s3ForcePathStyle: true
          secretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
          accessKeyId: "${AWS_ACCESS_KEY_ID}"
      auth_enabled: false
      schemaConfig:
        configs:
          - from: "2024-08-01"
            object_store: s3
            store: tsdb
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      tracing:
        enabled: true
      ingester:
        chunk_encoding: snappy
      querier:
        max_concurrent: 4
    minio:
      enabled: false
    deploymentMode: SimpleScalable
    backend:
      extraEnv:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: loki-s3-credentials
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: loki-s3-credentials
              key: secret_key
      extraArgs:
        - -config.expand-env=true
      replicas: 3
    read:
      extraEnv:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: loki-s3-credentials
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: loki-s3-credentials
              key: secret_key
      extraArgs:
        - -config.expand-env=true
      replicas: 3
    write:
      extraEnv:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: loki-s3-credentials
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: loki-s3-credentials
              key: secret_key
      extraArgs:
        - -config.expand-env=true
      replicas: 3
    # Zero out replica counts of other deployment modes
    singleBinary:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0

