---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: all-alerts
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventMetadata:
    env: "production"
    cluster: "infra-prod"
    region: "ams3"
  eventSources:
    - kind: Bucket
      name: "*"
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"
    - kind: HelmChart
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: ImageRepository
      name: "*"
    - kind: ImagePolicy
      name: "*"
    - kind: ImageUpdateAutomation
      name: "*"
  exclusionList:
    - "^Dependencies do not meet ready condition.*"
