---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: discord-alerts
  namespace: flux-system
spec:
  interval: 10m
  path: "cluster/flux-alerts/discord_alerts/"
  dependsOn:
    - name: 1password-connect
      namespace: 1pwd
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
