---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord
  namespace: flux-alerts
spec:
  type: discord
  channel: monitoring
  secretRef:
    name: discord-url
