---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: scouterbee-secrets
  namespace: scouterbee
spec:
  interval: 5m
  path: "cluster/scouterbee/secrets"
  dependsOn:
    - name: 1password-connect
      namespace: 1pwd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
