---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: scouterbee
  namespace: scouterbee
spec:
  interval: 5m
  path: "cluster/scouterbee/service"
  dependsOn:
    - name: scouterbee-secrets
      namespace: scouterbee
    - name: cert-manager
      namespace: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
