---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: studentbee-frontend
    component: frontend
    part-of: beehive
    project: exam.login.no
    confidentiality: not-defined
    compliance: not-defined
  name: studentbee-frontend
  namespace: studentbee
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: studentbee-frontend
  template:
    metadata:
      labels:
        app: studentbee-frontend
        component: frontend
        part-of: beehive
        project: exam.login.no
        confidentiality: not-defined
        compliance: not-defined
    spec:
      imagePullSecrets:
        - name: gitlab-deploy-key-studentbee
      containers:
        - name: webserver
          image: registry.login.no/tekkom/web/beehive/exam.login.no/frontend:2.3.4@sha256:d6f3a2cbc743be3c345ac8189bcfbf6c19a08c3318237ccedb20e86a0e01d1f2
          imagePullPolicy: IfNotPresent
          env:
            - name: API_URL
              value: http://studentbee-api.studentbee.svc.cluster.local:8080/api
            - name: NEXT_PUBLIC_BROWSER_API_URL
              value: https://exam-api.login.no/api
          ports:
            - containerPort: 3000
              name: 3000tcp
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: 128Mi
              cpu: 125m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - studentbee-frontend
                topologyKey: kubernetes.io/hostname
