# General network policies for the dizambee namespace
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: dizambee
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-all-ingress-except-tekkombot
  namespace: dizambee
spec:
  podSelector:
    matchLabels:
      app: dizambee-api

  policyTypes:
    - Ingress

  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: tekkom-bot
      - podSelector:
          matchLabels:
            app: tekkom-bot
