---
apiVersion: v1
kind: Secret
metadata: 
  name: gitlab-saml
  namespace: gitlab
type: Opaque
data: 
  saml.yaml: |
  name: 'saml'
  label: 'authentik'
  args:
    assertion_consumer_service_url: 'https://gittest.login.no/users/auth/saml/callback'
    idp_cert_fingerprint: 25:79:61:b4:65:2d:6c:12:1c:b2:bc:b5:1e:5b:fa:4e:e0:07:67:22
    idp_sso_target_url: 'https://authentik.login.no/application/saml/gitlab-application/sso/binding/redirect/'
    issuer: 'https://gittest.login.no'
    name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'