## https://github.com/zammad/zammad-helm/blob/main/zammad/values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zammad-prod
  namespace: zammad
spec:
  interval: 10m
  chart:
    spec:
      chart: zammad
      version: "12.3.2"
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: zammad
      interval: 5m
  values:
    ingress:
      enabled: true
      ingressClassName: nginx-ntnu
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/upgrade-proxy: "true"
        nginx.ingress.kubernetes.io/enable-websockets: "true"
      tls:
        - hosts:
            - zammad-test.login.no
      hosts:
        - host: zammad-test.login.no
          paths:
            - path: "/"
              pathType: Prefix

    postgresql:
      auth:
        username: "zammad"
        replicationUsername: repl_user
        database: "zammad_production"
        # Passwords
        postgresPassword: "zammad"
        password: "zammad"
        replicationPassword: "zammad"

    redis:
      auth:
        password: zammad

    zammadConfig:
      postgresql:
        # enable/disable postgresql chart dependency
        enabled: true
        # needs to be the same as the postgresql.auth.database
        db: zammad_production
        # host env var is only used when postgresql.enabled is false
        host: zammad-postgresql
        # needs to be the same as the postgresql.auth.password
        pass: "zammad"
        port: 5432
        # needs to be the same as the postgresql.auth.username
        user: zammad
      redis:
        # enable/disable redis chart dependency
        enabled: true
        host: "zammad-redis-master"
        # needs to be the same as the redis.auth.password
        pass: zammad
        port: 6379