---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zammad-prod
  namespace: zammad
spec:
  interval: 5m
  chart:
    spec:
      chart: zammad
      version: "10.0.0"
      sourceRef:
        kind: HelmRepository
        name: zammad-repo
        namespace: zammad
      interval: 1m
  values:
    replicas: 1
    image:
      repository: ghcr.io/zammad/zammad
      tag: "latest"
      pullPolicy: IfNotPresent
      imagePullSecrets: []

    service: 
      type: ClusterIP
      port: 8080
    