---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zammad-prod
  namespace: zammad
spec:
  interval: 5m
  chart:
    spec:
      chart: zammad
      version: "10.0.0"
      sourceRef:
        kind: HelmRepository
        name: zammad-repo
        namespace: zammad
      interval: 1m