---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipa-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: do-block-storage
