---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  blueprints.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata: 
      name: gitlab

    entries: 
      - model: authentik_providers_saml.samlprovider
        state: present
        conditions: []
        identifiers:
          pk: 1
        id: gitlab-provider
        attrs:
          name: gitlab-provider
          issuer: https://gittest.login.no
          audience: https://gittest.login.no
          acs_url: https://gittest.login.no/users/auth/saml/callback
          assertion_valid_not_before: minutes=-5
          assertion_valid_not_on_or_after: minutes=5
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          digest_algorithm: http://www.w3.org/2001/04/xmlenc#sha256
          property_mappings:
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: WindowsAccountname (Username)']]
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: Username']]
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: UPN']]
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: Email']]
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: Groups']]
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: User ID']]
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: Name']]
          session_valid_not_on_or_after: minutes=86400
          signature_algorithm: http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
          signing_kp: !Find [authentik_crypto.certificatekeypair, [name, authentik_cert]]
          sp_binding: redirect
      
      - model: authentik_core.application
        state: present
        identifiers:
          slug: gitlab-application
        id: gitlab-application
        attrs:
          name: gitlab-application
          policy_engine_mode: all
          provider: 1
          slug: gitlab-application

      - model: authentik_providers_saml.samlprovider
        state: present
        conditions: []
        identifiers:
          pk: 1
        id: wiki-provider
        attrs:
          name: wiki-provider
          issuer: https://wikitest.login.no
          audience: https://wikitest.login.no
          acs_url: https://wikitest.login.no/users/auth/saml/callback
          assertion_valid_not_before: minutes=-5
          assertion_valid_not_on_or_after: minutes=5
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          digest_algorithm: http://www.w3.org/2001/04/xmlenc#sha256
          property_mappings:
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: WindowsAccountname (Username)']]
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: Username']]
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: UPN']]
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: Email']]
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: Groups']]
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: User ID']]
          - !Find [authentik_providers_saml.samlpropertymapping, [name, 'authentik default SAML Mapping: Name']]
          session_valid_not_on_or_after: minutes=86400
          signature_algorithm: http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
          signing_kp: !Find [authentik_crypto.certificatekeypair, [name, authentik_cert]]
          sp_binding: redirect
      
      - model: authentik_core.application
        state: present
        identifiers:
          slug: wiki-application
        id: wiki-application
        attrs:
          name: wiki-application
          policy_engine_mode: all
          provider: 1
          slug: wiki-application